import React from 'react'
import './DajakBoath.scss';
import pic from '../img/camac.jpg'
import img from '../img/img-04.jpg'

const DajakBoath = () => {
  return (

    <div class='post'>
        <img src={pic} />
        <div class="text-holder">

                <h2>DAJAK ČAMAC</h2>

                <p>Davno još, dok su zemljom hodali divovi i patuljci, Vrbas je krao srebrnu krljušt sa zmajevih krila, žednih čuvara mašte i velikog blaga u brdima, dok bi jednom godišnje silazili iz skrovišta na kamene obale rijeke da piju zelenu vodu. Baš tako, u to doba na brdu pored sadašnjeg grada živio je jedan takav div sa svojim novorođenim sinom. Pošto je bilo vrijeme da zemlju nasele ljudi, Bog posla veliku vodu, a brdo na kom je div živio odluči pretvoriti u vulkan koji spali sve ono što voda nije progutala. Ipak prije kraja svoga svijeta i života, stari div predosjeti nesreću i napravi čamac u kog stavi novorođenče. Sinu dade ime Bajalukan. Zatim pozva orla i reče mu da ga odnese na neko sigurnije mjesto. Orao ga posluša i čamac sa đetetom prenese na visoki greben kojeg voda nije potopila, a ispod kog će mnogo vijekova kasnije niknuti veliki grad. Voda se povuče, vulkan utihnu, Bajalukan odraste i osnova naselje, orodi se sa ljudima a čamac koji mu napravi otac sa grebena kog su otomanski osvajači kasnije prozvali Šehitluci, spusti na Vrbas. Za svakog u spomen osta po nešto. Vulkansko brdo ljudi prozvaše Tutnjevac, naselje Bajalukanovo- Banjalukom, a čamci koje gradiše na Vrbasu nalikovaše prvom Vrbaskom čamcu divovskog đeteta. Špic čamca imao je oblik orlovskog kljuna u čast ptici koja spasi dijete od potopa. Ljudski potomci Bajalukana koji su vozili čamce imaše krupnu građu i divovsku snagu, Vrbasa se ne bojaše, vremenom ga dobro upoznaše i toliko zavolješe da ta ljubav traje i danas. A nama, danjašnjim Banjalučanima u spomen osta ova izmišljena legenda i ovaj pravi živi spomenik sa orlovskom glavom na špicu- Vrbaski čamac sa dajakom. A poneki Bajalukanov potomak, naš savremenik, ima sposobnost da čita vodu, što mu osta od starog diva koji je predosjetio nesreću. Voda ima mnogo šta da kaže a ovo je priča o ljudima koji je dobro poznaju, vole, voze Vrbaske čamce i koji između sna i jave traže davno ukradenu zmajevu srebrnu krljušt.</p>
                <p>Naravno da ovu priču ne mogu da potkrijepim ni jednim naučnim dokazom sem čika Jeftinih riječi sigurno je tako bilo a od njega sam je i čuo prije nego što je odlutao u neki novi mitski svijet drevnih naroda.</p>
                <p>Pretpostavka je da je Vrbaski čamac nastao kada i Banjaluka- grad na dvije obale Vrbasa, prvo zato što nije bilo mostova pa je čamac bio jedino riješenje za prelazak sa obale na obalu, a kasnije kada su sagrađeni prvi mostovi- bio je jedini način prelaska preko rijeke a da se ne plati mostarina. Tokom stoljeća ovo neobično plovilo je postalo simbolom grada, ostavivši traga u kulturi Banjalučana. Korišten je u trgovačke svrhe, za prevoz robe kako od obale do obale tako uz vodu ili niz vodu, vjerovatno brže nego tadašnjim saobraćajnicama. Pošto je roba bila skupocjena, a prevoz Vrbasom nije savršeno siguran, umijeće vožnje čamca postalo je važno i izjednačilo se sa vrijednošću čamca kao spretnog prevoznog sredstva. Dobri vozači postajali su daleko čuveni i dobro plaćeni za svoje usluge. Specifičan splet okolnosti uslovio je radijus plovidbe na 15 kilometara jezgra naselja kroz koje protječe rijeka male dubine uz obale i pogodnog dna za odgurivanje motkom a ne veslanje. Upravo ta motka koja služi za odgurivanje daje čamcu potrebno ubrzanje za rijeku promjenjive struje i jakih padova vode relativno male dubine gdje veslo ne bi bilo od pomoći. Ta motka ima poseban špic ili šticu iz dva spojena dijela. Prvi dio je komad metalne cijevi u koji ulazi motka ili kako ćemo je od sada zvati- dajak, a na koju se nastavlja oštri čelični špic velike tvrdoće, posebno obrađen u kovačnicama. Štica je dugačka do 25cm, a pored visoke tvrdoće treba da posjeduje optimalnu težinu zbog balansa dajaka. Sam dajak je dugačak četiri metra i treba da je što lakši. Izrađuje se od jelove građe najveće kvalitete i pravilnih godova bez bilo kakvih nepravilnosti u drvetu ili mehaničkih oštećenja. Dajak se obrađuje hoblanjem, bez daljnje obrade impregnatorskim sredstvima ili lakiranjem. Valjkastog je oblika, obima 9 cm, a treba da je dovoljno gladak da ne stvara povrede na rukama vozača, a u isto vrijeme dovoljno hrapav da ne klizi iz ruku. Zato se izradi dajaka posvećuje posebna pažnja. Dužina od 4 metra je najpraktičnija, jer je tada i dovoljno lagan i podesan za brze pokrete i promjene položaja na vodi. Vrbas je pogodan za vožnju dajakom samo u onih 10-15 km specifičnog riječnog dna koje se sastoji od šljunka, kamena i sedre koji se naizmjenično mijenjaju u samom gradu. Ta teritorija je danas svedena od Ilidžanskog mosta u Gornjem Šeheru do vrbaske Ade (Rebrovački most). Još šezdesetih godina na Vrbasu se mogla vidjeti i Vrbaska lasta, čamac sa dva špica, na pramcu i na krmi, tako da je vožnja bila moguća sa oba kraja čamca. Ta vrsta čamca u Banjaluci je danas nažalost nestala, ali je važno spomenuti jer je i Lasta takođe bila pokretana dajakom.</p>
                <p>Sam Vrbaski čamac, još od svog postanka imao je specifičan izgled i oblik trupa u svemu prilagođen brzom Vrbasu. Dužine su varirale od 6- 9 metara, a širine od 70cm. do 1m. u zavisnosti od namjene i mjesta na kom se nalazio ili majstora koji ga je pravio. Težina je varirala od 120 do 180kg. zbog tereta katrana kojim je čamac premazivan kao zaštitno sredstvo. Za predpostaviti je da je nekada u Banjaluci živjelo mnogo majstora koji su ga pravili, pa je od njihove umješnosti i iskustva sa vode zavisio izgled čamca. Prije i poslije Drugog svijetskog rata čamac je bio statusni simbol porodice koja ga je posjedovala i pokazatelj imućnosti vlasnika. Baš zbog te stvari Vrbaski čamac je duboko usađen u kulturno naslijeđe Banjaluke, a ljudi koji su ga vozili bili su zdravi mentalno i fizički, zbog svoje spretnosti i hrabrosti kretanja na vodi, pogotovo što je ljudska populacija u to doba bila manje okrenuta vodi i plivački obrazovana nego danas, što je ukupno donosilo posebnu popularnost dajakašima a samim tim i njihovu porodicu činilio poznatom i primamljivom za potencijalne ženidbe i udaje, kao i trgovinu, pa eto tako dajaci zauzimaju svoje mjesto i u ovom segmentu razvoja Banjaluke.</p>
                <p>Vožnja čamca je poseban dio ove priče pa ću i njoj posvetiti nekoliko redova.</p>
                <p>Gura se stojeći sa krme, lijeva noga je izbačena malo naprijed i stoji pravo na posebnoj drvenoj letvici pričvršćenoj na dno čamca i služi kao oslonac za prste lijeve noge koja prima veliku silu pri vožnji, a sa njom se i balansira pri skretanju sa pravca vožnje ili kontroli tereta u čamcu. Desna noga stoji svojim desnim bridom pete uz samu krmu, a na njoj je i glavni oslonac tijela. Gura se rukama sa desne strane čamca i to čitavim dajakom, tako što se dajak zabode u dno otprilike kod letvice za lijevu nogu i odguruje čitavom dužinom iza čamca, dok desna ruka vuče dajak a lijeva ga gura, a zatim ponovo izvlači iz vode. Za ovako nešto potrebno je imati savršenu ravnotežu, pogotovo na nemirnoj vodi. Ovi ubodi nazivaju se šupovi i što su pravilniji to čamac brže ide. Skreće se bacanjem dajaka iza sebe- lijevo, a od sebe- desno. Moguće je i kormilariti dajakom, ali se tako gubi ubrzanje. Vozi se uz obalu ali i na svim terenima koji to omogućavaju koristeći pogodnu dubinu do dva metra i prelazeći iz virova koji se stvaraju iza stijena koje vire iz vode ili su do same površine, koristeći prirodnu tihu koja se stvara iza njih. Ove tihe se nazivaju kontratokovi i iskusnom vozaču su velika pomoć u vožnji.</p>
                <p>Novija istorija Vrbaskog čamca, recimo zadnjih četrdeset godina, bez ikakve sumnje se veže na ljude kojima i danas treba odati priznanje zbog svog zalaganja za očuvanje ove toliko ugrožene tradicije, na sve one koji su nekoga naučili da vozi čamac, ili su ga sami napravili, barem provozali i ispričali dio ove priče, ali najviše dvojici braće iz stare banjalučke porodice talijanskog porijekla Mariu i Antoniu Zamolo. Smisao za tehniku i veliku sklonost ka radu i stvaranju raznih praktičnih stvari naučili su od oca Guida, vlasnika i vrsnog majstora zlatarskog i sajdžijskog zanata čija je radnja bila smještena još davno prije Drugog rata, u samoj Gospodskoj ulici. Gradsko okruženje i sam život pored rijeke uslovili su da se ova dva brata često susreću sa čamcima, čija ih je izrada i vožnja oduvijek privlačila. U vremenu poslije rata broj čamaca nije bio veliki jer su ih njemački vojnici tokom okupacije oduzeli i zatvorili u Kastel, gdje je veliki broj i propao, a u periodu poslijeratnog opšteg siromaštva malo njih je moglo da se pohvali da posjeduje nov čamac. Situacija se sa godinama popravljala, čak se i održavaju i godišnje trke čamaca a o pobjedniku se pričalo čitavu godinu, do iduće trke. I tako sve do 1964 god. kada iz radionice braće Zamolo izlazi prvi čamac imena LOTOS, a mlađi brat Atonio- Tonči postaje respektivan vozač kog su poštovali mnogo stariji i iskusniji vozači. Niko nije ni slutio da će se slogan Tonči i Lotos i danas u dajakaškim krugovima kao i u čitavoj Banjaluci izgovarati sa velikim poštovanjem.</p>
                <p>Taj čamac je prvi od današnjih Vrbaskih čamaca sa dajakom koji uz izvjesne prepravke i dorade u kasnijim šezdesetim godinama dobijaju savremen izgled. S obzirom da ne raspolažem tačnim podacima o nekadašnjem Vrbaskom čamcu nisam se ni upuštao u opisivanje, a pošto je pojavom Tončijevog čamca došlo do velike popularizacije ovog plovila u čitavoj Banjaluci zbog posebne elegancije i izgleda na vodi, kao i plovnih karkteristika- taj tip čamca svakako vrijedi opisati i upoznati se sa njim.</p>
                <p>Vrbaski čamac je prvo dobio stalnu dužinu od sedam metara kao najpraktičniju spram svoje konstrukcije od 3 metalna rebra unutar trupa. Debljina daske je 1,5 cm, najveća širina čamca je 75cm, dubina 30cm, gaz praznog plovila 12cm; krase ga visoka kvaliteta izrade, impregnacije i završne obrade. Najupečatljiviji detalji su krma i špic koji se izrađuju od jednog komada drveta- bagrema, jasena, hrasta, rjeđe trešnje, pa čak i mahagonija. To su materijali koji se različito ponašaju pri obradi, ali treba da ih krasi čistoća i pravilnost godova i koji po završetku obrade daju poseban izgled čamcu zbog svoje prirodne boje i oblika. Špic je tetovaža na čamcu koju on nosi od postanka do nestanka, upečatljiviji je od imena čamca, ali što je još upečatljivije- zaista izgleda poput neke mitske životinje, orla ili zmaja, odaje pitomost ili agresivnost, umjetničku viziju majstora koja je svaki put različita, tako da svaki čamac krasi drugačiji špic. Baš zbog špica vrbaski čamac nije samo puki predmet, on je pravo umjetničko dijelo. I sama izrada čamca je umjetnost preciznosti. Tonči je napravio malu revoluciju u izradi trupa, jer izbacuje katran iz upotrebe i time značajno smanjuje težinu, tako da ni najteži čamac ne prelazi 120kg., uvodi bezbojni lak i unutrašnje spajanje dasaka čime dobija na čvrstoći. Poneki detalj treba da ostane tajna- sklapanje, obrada, upotreba alata, postojanost materijala koji se koriste u izradi i njihovo međusobno ponašanje su i za autora ovog članka donekle nepoznanica čiji naziv glasi- koza nostra- dakle, tajne zanata porodice Zamolo.</p>
        </div>

        <div className='image-holder'>
          <img src={img} />
        </div>
           
            
    </div>
  )
}

export default DajakBoath